### PR TITLE
make colour_carrier_all channel work and crafting

### PR DESCRIPTION
**Pull request by Desour**
This should have been done already since months. I mean, the code was absolutely nonsense!
The changes are tested and work well.

### CODE REVIEW

**Comment by Desour** [comment]
I was confused and so made the crafting commit to master, too. So, I couldn't make a separate PR, sorry.

**Comment by DS-Minetest** [comment]
I'll merge this.

**Comment by Desour** [comment]
Perhaps I should have rebased it. But idk exactly what that does.

**Comment by HybridDog** [comment]
rebase braucht man bei PRs eigentlich nur, wenn bei der Original Repository Änderungen an den gleichen Stellen gemacht wurden

**Comment by Desour** [comment]
Ah, achso, ok, gut, dann passt es ja. :cat2::rainbow_flag:

**Pull request merged**
